# Generated by Django 5.2 on 2026-05-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='desarrolladora',
            new_name='desarolladora',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='generos',
            field=models.ManyToManyField(blank=True, to='catalogo.genero'),
        ),
    ]
