# Generated by Django 5.2 on 2026-05-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='desarolladora',
            new_name='desarrolladora',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(to='catalogo.plataforma'),
        ),
    ]
